name: Generate snake game

# Give the workflow permission to push to the repository, which is necessary for updating the SVG file and deploying to GitHub Pages.
permissions:
  contents: write

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo so the action can work with it
      - name: Checkout
        uses: actions/checkout@v4

      # Snake Animation
      - name: Generate snake SVG
        uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Deploy to output branch
      - name: Deploy to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
